In [7]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup
import html5lib
from selenium.webdriver import Chrome
import warnings
warnings.filterwarnings("ignore")

In [6]:
driver = Chrome(executable_path="C://Kiki/chromedriver.exe")
url = "https://coinbase.com/explore" 
driver.get(url)

In [ ]:
soup = BeautifulSoup(driver.page_source,"html5lib")

In [ ]:
tr = soup.find("table",class_="cds-table-top40r1").tbody.find_all("tr")

In [ ]:
data = pd.DataFrame(columns=["name","value"])
for i in range(0,len(tr)):
    print(tr[i].find("h2").text)
    print(tr[i].find("div",class_="cds-flex-f1g67tkn cds-flex-end-f9tvb5a cds-column-ci8mx7v cds-flex-start-f1urtf06").text)
    data.loc[len(data)] = [tr[i].find("h2").text, tr[i].find("div",class_="cds-flex-f1g67tkn cds-flex-end-f9tvb5a cds-column-ci8mx7v cds-flex-start-f1urtf06").text]

Bitcoin
€21,201.68
Ethereum
€1,712.17
Ethereum 2
€1,712.17
Tether
€0.99
USD Coin
€0.98
BNB
€289.63
Binance USD
€0.98
XRP
€0.35
Cardano
€0.51
Solana
€34.42
Polkadot
€7.68
Dogecoin
€0.0636
Polygon
€0.88
SHIBA INU
€0.000013
Dai
€0.98
Avalanche
€20.23
TRON
€0.0626
Ethereum Classic
€38.79
Wrapped Bitcoin
€21,037.79
Uniswap
€6.53
UNUS SED LEO
€4.89
Cosmos
€15.80
Litecoin
€61.05
Chainlink
€7.66
NEAR Protocol
€4.66
FTX Token
€26.82
Crypto.com Coin
€0.12
Stellar Lumens
€0.11
Monero
€155.44
Terra
€0.000410

In [ ]:
data

                name       value
0            Bitcoin  €21,201.68
1           Ethereum   €1,712.17
2         Ethereum 2   €1,712.17
3             Tether       €0.99
4           USD Coin       €0.98
5                BNB     €289.63
6        Binance USD       €0.98
7                XRP       €0.35
8            Cardano       €0.51
9             Solana      €34.42
10          Polkadot       €7.68
11          Dogecoin     €0.0636
12           Polygon       €0.88
13         SHIBA INU   €0.000013
14               Dai       €0.98
15         Avalanche      €20.23
16              TRON     €0.0626
17  Ethereum Classic      €38.79
18   Wrapped Bitcoin  €21,037.79
19           Uniswap       €6.53
20      UNUS SED LEO       €4.89
21            Cosmos      €15.80
22          Litecoin      €61.05
23         Chainlink       €7.66
24     NEAR Protocol       €4.66
25         FTX Token      €26.82
26   Crypto.com Coin       €0.12
27    Stellar Lumens       €0.11
28            Monero     €155.44
29             Terra   €0.000410

In [8]:
driver.quit()